name: wellpathpy test and build action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.7, 3.8, 3.9, "3.10", 3.11]
    steps:
    - uses: actions/checkout@v2
    - name: Set up python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Run tests
      run: |
        python -m pytest
    - name: Build wheel
      run: |
        python -m build --wheel
